(()=>{
  const KEY='averon_consent_v1';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch(_){return null}};
  const save=(optional)=>{try{localStorage.setItem(KEY,JSON.stringify({version:1,necessary:true,optional:!!optional,updatedAt:new Date().toISOString()}))}catch(_){}; closeAll(); window.dispatchEvent(new CustomEvent('averon:consent',{detail:{optional:!!optional}}));};
  function closeAll(){document.querySelector('.cookie-banner')?.classList.remove('is-open');document.querySelector('.cookie-modal')?.classList.remove('is-open');document.body.style.overflow='';}
  function openSettings(){const m=document.querySelector('.cookie-modal');if(!m)return;const c=read();m.querySelector('[data-optional-toggle]').checked=!!c?.optional;m.classList.add('is-open');document.body.style.overflow='hidden';}
  const banner=document.createElement('div');banner.className='cookie-banner';banner.setAttribute('role','region');banner.setAttribute('aria-label','Cookie notice');banner.innerHTML=`<div class="cookie-banner-inner"><p><strong>Your privacy choices.</strong> AVERON uses essential browser storage for requested store functions such as your bag and wishlist. Optional analytics/marketing technologies will remain off unless enabled where consent is required. <a href="cookie-policy.html">Cookie Policy</a>.</p><div class="cookie-actions"><button class="cookie-btn" data-reject>Essential only</button><button class="cookie-btn" data-settings>Settings</button><button class="cookie-btn primary" data-accept>Accept optional</button></div></div>`;document.body.appendChild(banner);
  const modal=document.createElement('div');modal.className='cookie-modal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label','Cookie settings');modal.innerHTML=`<div class="cookie-panel"><div class="cookie-panel-head"><div><h2>Cookie settings</h2><p>Choose how optional technologies may be used.</p></div><button class="cookie-close" data-cookie-close aria-label="Close">×</button></div><div class="cookie-row"><div><strong>Essential functionality</strong><p>Used for requested store functions and security. These cannot be switched off here.</p></div><span class="cookie-status">Always on</span></div><div class="cookie-row"><div><strong>Optional analytics & marketing</strong><p>No optional analytics or advertising tracker is intentionally loaded in this build. This preference is stored so future integrations can respect your choice.</p></div><input class="cookie-toggle" type="checkbox" data-optional-toggle aria-label="Allow optional analytics and marketing"></div><div class="cookie-panel-actions"><button class="cookie-btn" style="color:#00293f;border-color:#00293f" data-essential>Essential only</button><button class="cookie-btn primary" style="background:#00293f;color:#fff;border-color:#00293f" data-save>Save choices</button></div></div>`;document.body.appendChild(modal);
  banner.querySelector('[data-reject]').onclick=()=>save(false);banner.querySelector('[data-accept]').onclick=()=>save(true);banner.querySelector('[data-settings]').onclick=openSettings;modal.querySelector('[data-essential]').onclick=()=>save(false);modal.querySelector('[data-save]').onclick=()=>save(modal.querySelector('[data-optional-toggle]').checked);modal.querySelector('[data-cookie-close]').onclick=closeAll;modal.addEventListener('click',e=>{if(e.target===modal)closeAll()});document.addEventListener('click',e=>{const b=e.target.closest('[data-cookie-settings]');if(b){e.preventDefault();openSettings()}});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAll()});
  if(!read()) banner.classList.add('is-open');
})();
